# Generated by Django 4.0.5 on 2022-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputimage',
            name='img',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
