# Generated by Django 4.0.5 on 2022-06-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_inputimage_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inputImage',
        ),
    ]
